server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  dir: D:\market2\src\main\resources\static\files\

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market2?serverTimezone=Asia/Seoul
    username: market2
    password: market1234

  jpa:
    hibernate:
      ddl-auto: update #create update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug